const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let token=localStorage.getItem('safescroll-token'),me=null,summary=null,warnings=[],sessions=[],insights=null;
const pages=[['⌂','Dashboard','dashboard'],['✦','AI Agent','agent'],['▥','Analytics','analytics'],['⚑','Safety Center','safety'],['◎','Goals','goals'],['◈','Privacy','privacy']];
const mins=s=>`${Math.floor(s/3600)}h ${Math.floor(s%3600/60)}m`;
async function api(path,opts={}){const r=await fetch(path,{...opts,headers:{...opts.headers,'Content-Type':'application/json',Authorization:`Bearer ${token}`}});if(r.status===401){logout();throw Error('Your session expired. Please sign in again.');}const d=r.status===204?{}:await r.json();if(!r.ok)throw Error(d.error||'Request failed.');return d;}
function nav(){$('#nav').innerHTML=pages.map(([i,n,id])=>`<button data-page="${id}">${i} &nbsp;${n}</button>`).join('');$$('#nav button').forEach(x=>x.onclick=()=>show(x.dataset.page));}
function toast(title,message){const x=document.createElement('div');x.className='toast';x.innerHTML=`<strong>${title}</strong>${message}`;$('#toasts').append(x);setTimeout(()=>x.remove(),4000);}
function authMode(register){$('#authTitle').textContent=register?'Create your SafeScroll account':'Sign in to your workspace';$('#authHint').textContent=register?'Use a 10+ character password. We never collect social-media passwords.':'Your real analytics appear only after your authorized activity is recorded.';$('#authSubmit').textContent=register?'Create account':'Sign in';$('#authSwitch').textContent=register?'I already have an account':'Create an account';$('#nameLabel').hidden=!register;$('#ageLabel').hidden=!register;$('#consentLabel').hidden=!register;$('#authForm').dataset.mode=register?'register':'login';}
function setIdentity(){if(!me)return;const name=me.displayName||me.email.split('@')[0];$('#title').innerHTML=`Good evening, ${name} <span>✦</span>`;$('#avatar').textContent=name.charAt(0).toUpperCase();$('#headerLogout').hidden=false;}
async function authenticate(e){e.preventDefault();const register=$('#authForm').dataset.mode==='register';$('#authError').textContent='';try{const body=register?{displayName:$('#authName').value,email:$('#authEmail').value,password:$('#authPassword').value,ageGroup:$('#authAge').value,consent:$('#authConsent').checked}:{email:$('#authEmail').value,password:$('#authPassword').value};const r=await fetch(register?'/auth/register':'/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),d=await r.json();if(!r.ok)throw Error(d.error);token=d.token;me=d.user;localStorage.setItem('safescroll-token',token);$('#authGate').hidden=true;setIdentity();await refresh();show('dashboard');}catch(err){$('#authError').textContent=err.message;}}
function logout(){localStorage.removeItem('safescroll-token');token=null;me=null;summary=null;$('#headerLogout').hidden=true;$('#title').innerHTML='Welcome to SafeScroll <span>✦</span>';$('#avatar').textContent='S';$('#authGate').hidden=false;authMode(false);}
async function refresh(){[summary,warnings,sessions,insights]=await Promise.all([api('/analytics/summary'),api('/analytics/warnings'),api('/analytics/sessions'),api('/analytics/insights')]);}
function empty(){return `<div class="card" style="margin-top:15px"><h3>No activity recorded yet</h3><p style="color:var(--muted);font-size:13px;line-height:1.7">This account starts at zero. Start AI Guard, then use the connected browser extension on YouTube or Instagram to create real session records.</p></div>`;}
function monitoringCard(){const active=summary.monitoringEnabled,used=Math.min(100,summary.totalSeconds/(summary.dailyGoalMinutes*60)*100);return `<div class="card agent-status ${active?'bot-active':''}"><h3><span class="agent-pulse"></span>AI Guard ${active?'ACTIVE':'PAUSED'}</h3><p>${active?'Monitoring new authorized extension events.':'No new browser events will be accepted.'}</p><button id="monitorToggle" class="btn ${active?'ghost':'primary'}">${active?'Pause AI Guard':'Start AI Guard'}</button><div class="progress" style="margin-top:14px"><span style="width:${used}%"></span></div><p>Daily goal: ${mins(summary.dailyGoalMinutes*60)} · ${mins(summary.totalSeconds)} recorded</p></div>`;}
function bindMonitor(){const b=$('#monitorToggle');if(b)b.onclick=async()=>{try{const next=!summary.monitoringEnabled;await api('/monitoring',{method:'PATCH',body:JSON.stringify({enabled:next})});await refresh();toast(next?'AI Guard started':'AI Guard paused',next?'Open or refresh a supported tab to begin tracking.':'Active sessions were safely ended.');show($('.page.active').id);}catch(e){toast('Unable to update AI Guard',e.message);}};}
function dashboard(){const has=!summary.empty;$('#dashboard').innerHTML=`<div class="page-head"><div><h2>Welcome, ${me.displayName||me.email.split('@')[0]}</h2><p>Private records for this account only.</p></div><button id="signOut" class="btn ghost">Sign out</button></div><div class="kpis"><div class="card"><div class="kpi-label">TODAY'S ACTIVITY</div><div class="kpi-value">${mins(summary.totalSeconds)}</div><span class="delta">Actual session duration</span></div><div class="card"><div class="kpi-label">DAILY GOAL</div><div class="kpi-value">${mins(summary.dailyGoalMinutes*60)}</div><span class="delta">Configurable</span></div><div class="card"><div class="kpi-label">SESSIONS</div><div class="kpi-value">${summary.sessions}</div><span class="delta">No duplicate active sessions</span></div><div class="card"><div class="kpi-label">LONGEST SESSION</div><div class="kpi-value">${mins(summary.longestSeconds)}</div><span class="delta">Today</span></div><div class="card"><div class="kpi-label">SAFETY WARNINGS</div><div class="kpi-value">${summary.warnings}</div><span class="delta ${summary.warnings?'down':''}">${summary.dismissedWarnings} dismissed</span></div></div><div class="grid"><div class="card span2"><h3>Platform activity</h3>${has?summary.platforms.map(x=>`<div class="platform" style="--dot:#6d64f7"><i></i><span>${x.platform}</span><b>${mins(x.seconds)}</b><div class="progress"><span style="width:${summary.totalSeconds?x.seconds/summary.totalSeconds*100:0}%"></span></div></div>`).join(''):'No platform activity yet.'}</div>${monitoringCard()}</div>${has?`<div class="row2"><div class="card"><h3>Recent sessions</h3>${sessions.slice(0,5).map(s=>`<div class="timeline-item"><small>${new Date(s.started_at).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</small><b>${s.platform}</b><span class="tag">${mins(s.duration_seconds||0)}</span></div>`).join('')}</div><div class="card"><h3>Content signals</h3>${summary.categories.map(x=>`<div class="platform" style="--dot:#36bc95"><i></i><span>${x.category}</span><b>${x.count}</b></div>`).join('')}</div></div>`:empty()}`;$('#signOut').onclick=logout;bindMonitor();}
function agent(){$('#agent').innerHTML=`<div class="page-head"><div><h2>AI Safety Agent</h2><p>Start or pause monitoring at any time. Pausing immediately closes active sessions.</p></div></div><div class="grid">${monitoringCard()}<div class="card span2"><h3>Connected browser workflow</h3><p style="font-size:13px;color:var(--muted);line-height:1.7">When active, AI Guard processes permitted browser-visible titles/descriptions from your extension. It calculates warnings from your actual session duration and age policy. When paused, it rejects new events and stops time accumulation.</p><button id="copyToken" class="btn primary">Copy extension token</button></div></div>`;$('#copyToken').onclick=async()=>{await navigator.clipboard.writeText(token);toast('Token copied','Paste it into the extension Options page.');};bindMonitor();}
function statList(rows,label){return rows.length?rows.map(x=>`<div class="platform" style="--dot:#36bc95"><i></i><span>${x[label]}</span><b>${x.count}</b></div>`).join(''):'<p style="color:var(--muted);font-size:12px">No signals yet.</p>';}
function analytics(){$('#analytics').innerHTML=`<div class="page-head"><div><h2>Advanced analytics</h2><p>Real records only · analysis is based on permitted browser-visible metadata.</p></div><button id="reload" class="btn ghost">Refresh</button></div>${summary.empty?empty():`<div class="grid"><div class="card"><h3>Sentiment</h3>${statList(insights.sentiment,'sentiment')}</div><div class="card"><h3>Emotional signals</h3>${statList(insights.emotion,'emotion')}</div><div class="card"><h3>Stance signals</h3>${statList(insights.stance,'stance')}</div></div><div class="row2"><div class="card"><h3>Rising topics · last 7 days</h3>${statList(insights.trends,'topic')}<p style="font-size:11px;color:var(--muted)">Topics are ranked from your own chronological event history; no claim is made about platform-wide trends.</p></div><div class="card"><h3>Demographic insights</h3><p style="font-size:12px;color:var(--muted);line-height:1.7">${insights.demographics.message}</p><span class="tag">OFFICIAL AGGREGATE INSIGHTS REQUIRED</span></div></div><div class="card"><h3>Session history</h3><table class="table"><tr><th>PLATFORM</th><th>STARTED</th><th>DURATION</th></tr>${sessions.map(x=>`<tr><td>${x.platform}</td><td>${new Date(x.started_at).toLocaleString()}</td><td>${mins(x.duration_seconds||0)}</td></tr>`).join('')}</table></div>`}`;$('#reload').onclick=async()=>{await refresh();analytics();};}
function safety(){$('#safety').innerHTML=`<div class="page-head"><div><h2>Safety center</h2><p>Warnings from real analysis only.</p></div></div>${warnings.length?`<div class="card">${warnings.map(w=>`<div class="alert"><div class="alert-icon">${w.severity==='high'?'🛡':'⚠'}</div><div><b>${w.warning_type.replace('_',' ')}</b><p>${w.message}</p><small>${new Date(w.shown_at).toLocaleString()} ${w.dismissed_at?'· Dismissed':''}</small>${!w.dismissed_at?`<br><button class="btn ghost" data-dismiss="${w.id}">Dismiss</button>`:''}</div></div>`).join('')}</div>`:empty()}`;$$('[data-dismiss]').forEach(b=>b.onclick=async()=>{await api(`/warnings/${b.dataset.dismiss}/dismiss`,{method:'POST'});await refresh();safety();});}
function goals(){$('#goals').innerHTML=`<div class="card"><h3>Daily wellbeing goal</h3><p style="color:var(--muted);font-size:13px">Your current goal is used for progress only; it does not block applications.</p><form id="goalForm" class="flow"><label>Minutes per day <input id="goalInput" type="number" min="15" max="1440" value="${summary.dailyGoalMinutes}" style="width:85px;padding:7px;border:1px solid var(--line);border-radius:6px"></label><button class="btn primary">Save goal</button></form></div>`;$('#goalForm').onsubmit=async e=>{e.preventDefault();await api('/monitoring',{method:'PATCH',body:JSON.stringify({enabled:summary.monitoringEnabled,dailyGoalMinutes:Number($('#goalInput').value)})});await refresh();toast('Goal saved','Your dashboard progress is updated.');goals();};}
function privacy(){$('#privacy').innerHTML=`<div class="privacy-grid"><div class="card"><h3>Account separation</h3><ul><li>Each SafeScroll account has isolated sessions, events, warnings, and analytics.</li><li>A new account begins with zero activity.</li></ul></div><div class="card"><h3>Data minimisation</h3><ul><li>No social-media passwords, cookies, or messages.</li><li>Only permitted page metadata required for analysis.</li></ul></div></div>`;}
function show(id){$$('.page').forEach(x=>x.classList.toggle('active',x.id===id));$$('#nav button').forEach(x=>x.classList.toggle('selected',x.dataset.page===id));({dashboard,agent,analytics,safety,goals,privacy})[id]();}
$('#authForm').onsubmit=authenticate;$('#authSwitch').onclick=()=>authMode($('#authForm').dataset.mode!=='register');$('#theme').onclick=()=>document.body.classList.toggle('dark');$('#bell').onclick=()=>show('safety');$('#headerLogout').onclick=logout;nav();authMode(false);if(token)api('/auth/me').then(d=>{me=d.user;$('#authGate').hidden=true;setIdentity();return refresh();}).then(()=>show('dashboard')).catch(logout);
