const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let token=localStorage.getItem('safescroll-token'), me=null, summary=null, warnings=[];
const pages=[['⌂','Dashboard','dashboard'],['✦','AI Agent','agent'],['▥','Analytics','analytics'],['⚑','Safety Center','safety'],['◎','Goals','goals'],['◈','Privacy','privacy']];
const mins=s=>`${Math.floor(s/3600)}h ${Math.floor(s%3600/60)}m`;
async function api(path,opts={}){const r=await fetch(path,{...opts,headers:{...opts.headers,'Content-Type':'application/json',Authorization:`Bearer ${token}`}});if(r.status===401){logout();throw Error('Your session expired. Please sign in again.');}const d=r.status===204?{}:await r.json();if(!r.ok)throw Error(d.error||'Request failed.');return d;}
function nav(){ $('#nav').innerHTML=pages.map(([i,n,id])=>`<button data-page="${id}">${i} &nbsp;${n}</button>`).join('');$$('#nav button').forEach(x=>x.onclick=()=>show(x.dataset.page));}
function toast(title,message){const x=document.createElement('div');x.className='toast';x.innerHTML=`<strong>${title}</strong>${message}`;$('#toasts').append(x);setTimeout(()=>x.remove(),4000);}
function authMode(register){$('#authTitle').textContent=register?'Create your SafeScroll account':'Sign in to your workspace';$('#authHint').textContent=register?'Use a 10+ character password. We never collect social-media passwords.':'Your real analytics appear only after your authorized activity is recorded.';$('#authSubmit').textContent=register?'Create account':'Sign in';$('#authSwitch').textContent=register?'I already have an account':'Create an account';$('#ageLabel').hidden=!register;$('#consentLabel').hidden=!register;$('#authForm').dataset.mode=register?'register':'login';}
async function authenticate(e){e.preventDefault();const register=$('#authForm').dataset.mode==='register',email=$('#authEmail').value,password=$('#authPassword').value;$('#authError').textContent='';try{const body=register?{email,password,ageGroup:$('#authAge').value,consent:$('#authConsent').checked}:{email,password};const r=await fetch(register?'/auth/register':'/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(d.error);token=d.token;me=d.user;localStorage.setItem('safescroll-token',token);$('#authGate').hidden=true;await refresh();show('dashboard');}catch(err){$('#authError').textContent=err.message;}}
function logout(){localStorage.removeItem('safescroll-token');token=null;me=null;$('#authGate').hidden=false;authMode(false);}
async function refresh(){[summary,warnings]=await Promise.all([api('/analytics/summary'),api('/analytics/warnings')]);}
function empty(){return `<div class="card" style="margin-top:15px"><h3>No activity recorded yet</h3><p style="color:var(--muted);font-size:13px;line-height:1.7">Install the SafeScroll AI Guard extension and sign in with this account. Authorized YouTube or Instagram page metadata will create real session records here.</p></div>`}
function dashboard(){const has=!summary.empty;$('#dashboard').innerHTML=`<div class="page-head"><div><h2>Welcome, ${me.email.split('@')[0]}</h2><p>Real records only · ${has?'updated from your authorized activity':'no activity has been collected'}</p></div><button id="signOut" class="btn ghost">Sign out</button></div><div class="kpis"><div class="card"><div class="kpi-label">TODAY'S ACTIVITY</div><div class="kpi-value">${mins(summary.totalSeconds)}</div><span class="delta">Database calculated</span></div><div class="card"><div class="kpi-label">THIS WEEK</div><div class="kpi-value">${mins(summary.weeklySeconds)}</div><span class="delta">Recorded activity</span></div><div class="card"><div class="kpi-label">SESSIONS</div><div class="kpi-value">${summary.sessions}</div><span class="delta">Authorized browser sessions</span></div><div class="card"><div class="kpi-label">LONGEST SESSION</div><div class="kpi-value">${mins(summary.longestSeconds)}</div><span class="delta">Today</span></div><div class="card"><div class="kpi-label">SAFETY WARNINGS</div><div class="kpi-value">${summary.warnings}</div><span class="delta ${summary.warnings?'down':''}">${summary.dismissedWarnings} dismissed</span></div></div>${has?`<div class="grid"><div class="card span2"><h3>Platform activity</h3>${summary.platforms.map(x=>`<div class="platform" style="--dot:#6d64f7"><i></i><span>${x.platform}</span><b>${mins(x.seconds)}</b><div class="progress"><span style="width:${summary.totalSeconds?x.seconds/summary.totalSeconds*100:0}%"></span></div></div>`).join('')}</div><div class="card"><h3>Content analysis</h3>${summary.categories.map(x=>`<div class="platform" style="--dot:#36bc95"><i></i><span>${x.category}</span><b>${x.count}</b></div>`).join('')}</div></div>`:empty()}`;$('#signOut').onclick=logout;}
function agent(){ $('#agent').innerHTML=`<div class="page-head"><div><h2>AI Safety Agent</h2><p>🟢 Active when the browser extension is connected with your SafeScroll token.</p></div></div><div class="grid"><div class="card agent-status bot-active"><h3><span class="agent-pulse"></span>AI Guard ready</h3><p>It analyzes only permitted browser-visible metadata sent by the extension.</p><p><b>Session policies:</b> 30m notice · 45m break warning · 60m strong break recommendation</p></div><div class="card span2"><h3>Connect your browser</h3><p style="font-size:13px;color:var(--muted);line-height:1.7">Load the extension folder in Chrome/Edge Developer Mode. In the extension Options page, paste your SafeScroll access token from this browser’s local session. It will never request Instagram, YouTube, Facebook, or X passwords.</p><button id="copyToken" class="btn primary">Copy extension token</button></div></div>`;$('#copyToken').onclick=async()=>{await navigator.clipboard.writeText(token);toast('Token copied','Paste it into the extension Options page. Treat it like a password.');};}
function analytics(){ $('#analytics').innerHTML=`<div class="page-head"><div><h2>Analytics</h2><p>Derived only from persisted sessions and content events.</p></div><button class="btn ghost" id="reload">Refresh</button></div>${summary.empty?empty():`<div class="row2"><div class="card"><h3>Categories observed</h3><table class="table"><tr><th>CATEGORY</th><th>EVENTS</th></tr>${summary.categories.map(x=>`<tr><td>${x.category}</td><td>${x.count}</td></tr>`).join('')}</table></div><div class="card"><h3>Privacy note</h3><p style="font-size:12px;color:var(--muted);line-height:1.7">URLs/titles are used for the stated safety purpose. The extension does not collect passwords, cookies, private messages, or unrelated history.</p></div></div>`}`;const b=$('#reload');if(b)b.onclick=async()=>{await refresh();analytics();};}
function safety(){ $('#safety').innerHTML=`<div class="page-head"><div><h2>Safety center</h2><p>Each warning links to a real analysis result. Unverified claims are never stated as false.</p></div></div>${warnings.length?`<div class="card">${warnings.map(w=>`<div class="alert"><div class="alert-icon">${w.severity==='high'?'🛡':'⚠'}</div><div><b>${w.warning_type.replace('_',' ')}</b><p>${w.message}</p><small>${new Date(w.shown_at).toLocaleString()} ${w.dismissed_at?'· Dismissed':''}</small>${!w.dismissed_at?`<br><button class="btn ghost" data-dismiss="${w.id}">Dismiss</button>`:''}</div></div>`).join('')}</div>`:empty()}`;$$('[data-dismiss]').forEach(b=>b.onclick=async()=>{await api(`/warnings/${b.dataset.dismiss}/dismiss`,{method:'POST'});await refresh();safety();});}
function goals(){ $('#goals').innerHTML=`<div class="card"><h3>Digital wellbeing policy</h3><p style="font-size:13px;color:var(--muted);line-height:1.7">Continuous session thresholds are centrally enforced on the server: 30 minutes (notice), 45 minutes (break warning), and 60 minutes (stronger recommendation). User-specific configurable goals are the next database preference migration.</p></div>`;}
function privacy(){ $('#privacy').innerHTML=`<div class="privacy-grid"><div class="card"><h3>Collected</h3><ul><li>SafeScroll account email and hashed password.</li><li>Authorized platform session timestamps.</li><li>Page title, URL, and description metadata necessary for analysis.</li></ul></div><div class="card"><h3>Never collected</h3><ul><li>Social-media passwords or cookies.</li><li>Private messages or private account contents.</li><li>Unrelated browsing history.</li></ul></div></div>`;}
function show(id){$$('.page').forEach(x=>x.classList.toggle('active',x.id===id));$$('#nav button').forEach(x=>x.classList.toggle('selected',x.dataset.page===id));({dashboard,agent,analytics,safety,goals,privacy})[id]();}
$('#authForm').onsubmit=authenticate;$('#authSwitch').onclick=()=>authMode($('#authForm').dataset.mode!=='register');$('#theme').onclick=()=>document.body.classList.toggle('dark');$('#bell').onclick=()=>show('safety');nav();authMode(false);if(token)api('/auth/me').then(d=>{me=d.user;$('#authGate').hidden=true;return refresh();}).then(()=>show('dashboard')).catch(logout);
